version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
    
sphinx:
  fail_on_warning: true
  
python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
      
 # Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py
  fail_on_warning: false

formats:
  - pdf  
